#!/bin/sh

if test -e "$HOME"/.config/marla-os/firstboot-done; then
    echo "Already ran"
    exit 0
fi

(
echo "# Waiting for Internet connection"
until /usr/bin/ping -q -c 1 flathub.org; do sleep 1; done
echo "00"

echo "# Reticulating Final Splines"
mkdir -p "$HOME"/.config/marla-os/
touch "$HOME"/.config/marla-os/firstboot-done

) | 
     
   zenity --progress --title="Marla OS Desktop Firstboot" --percentage=0 --auto-close --no-cancel --width=300

if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Firstboot Configuration Error"
fi
